server:
  port: 8080
spring:
  application:
    name: reggie_take_out
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://upredic100:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  main:
    banner-mode: off  # 关闭 SpringBoot 启动图标(banner)
  cache:
    redis:
      time-to-live: 1800000
  data:
    redis:
      host: upredic100
      port: 6379
      password: 123456
      database: 0
      jedis:
        pool:
          max-active: 8
          max-wait: 1ms
          max-idle: 4
          min-idle: 0
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
    banner: off # 关闭 mybatis plus启动图标
reggie:
  path: D:\code\IdeaProjects\projects\reggie_alpha_upload_picture\